## Initial TED Talks Dataset Inspection

In [17]:
## Step 1: Import the required libraries 

import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [18]:
## Step 2: Load the dataset 

df = pd.read_csv("../data/raw/ted_talks.csv")

In [19]:
# Final column selection

# Column	        Why we need it?

# talk_id	        Unique identification of each talk
# title		        Displays the talk and helps identify its subject
# speaker_1	        Displays the primary speaker
# duration	        Supports recommendations based on available time
# topics	        Matches user interests with TED Talk topics
# url		        Provides the link to watch the recommended talk
# description		Provides a concise summary for content matching
# transcript		Provides detailed textual content for NLP-based recommendations

In [20]:
df.head()

,talk_id,title,speaker_1,duration,topics,url,description,transcript
0,1,Averting the climate crisis,Al Gore,977,"['alternative energy', 'cars', 'climate change...",https://www.ted.com/talks/al_gore_averting_the...,With the same humor and humanity he exuded in ...,"Thank you so much, Chris. And it's truly a gre..."
1,92,The best stats you've ever seen,Hans Rosling,1190,"['Africa', 'Asia', 'Google', 'demo', 'economic...",https://www.ted.com/talks/hans_rosling_the_bes...,You've never seen data presented like this. Wi...,"About 10 years ago, I took on the task to teac..."
2,7,Simplicity sells,David Pogue,1286,"['computers', 'entertainment', 'interface desi...",https://www.ted.com/talks/david_pogue_simplici...,New York Times columnist David Pogue takes aim...,"(Music: ""The Sound of Silence,"" Simon & Garfun..."
3,53,Greening the ghetto,Majora Carter,1116,"['MacArthur grant', 'activism', 'business', 'c...",https://www.ted.com/talks/majora_carter_greeni...,"In an emotionally charged talk, MacArthur-winn...",If you're here today â€” and I'm very happy th...
4,66,Do schools kill creativity?,Sir Ken Robinson,1164,"['children', 'creativity', 'culture', 'dance',...",https://www.ted.com/talks/sir_ken_robinson_do_...,Sir Ken Robinson makes an entertaining and pro...,Good morning. How are you? (Audience) Good. It...

In [21]:
## Step 3: Check the dataset dimensions 

print("Number of rows:", df.shape[0])

Number of rows: 4005

In [22]:
print("Number of columns:", df.shape[1])

Number of columns: 8

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4005 entries, 0 to 4004
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   talk_id      4005 non-null   int64
 1   title        4005 non-null   str
 2   speaker_1    4005 non-null   str
 3   duration     4005 non-null   int64
 4   topics       4005 non-null   str
 5   url          4005 non-null   str
 6   description  4005 non-null   str
 7   transcript   4005 non-null   str
dtypes: int64(2), str(6)
memory usage: 250.4 KB

In [24]:
df.shape

(4005, 8)

In [25]:
## Step 4: Display column names
print(df.columns.tolist())

['talk_id', 'title', 'speaker_1', 'duration', 'topics', 'url', 'description', 'transcript']

In [26]:
## Step 6: Check missing values
print(df.isnull().sum())

talk_id        0
title          0
speaker_1      0
duration       0
topics         0
url            0
description    0
transcript     0
dtype: int64

In [ ]:
## Step 7: Check duplicate rows
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [28]:
df.shape

(4005, 8)

In [29]:
print("Unique talk IDs:", df["talk_id"].nunique())

Unique talk IDs: 4005

In [30]:
df['duration'] = (df['duration']/60).round(2)
df.head()

,talk_id,title,speaker_1,duration,topics,url,description,transcript
0,1,Averting the climate crisis,Al Gore,16.28,"['alternative energy', 'cars', 'climate change...",https://www.ted.com/talks/al_gore_averting_the...,With the same humor and humanity he exuded in ...,"Thank you so much, Chris. And it's truly a gre..."
1,92,The best stats you've ever seen,Hans Rosling,19.83,"['Africa', 'Asia', 'Google', 'demo', 'economic...",https://www.ted.com/talks/hans_rosling_the_bes...,You've never seen data presented like this. Wi...,"About 10 years ago, I took on the task to teac..."
2,7,Simplicity sells,David Pogue,21.43,"['computers', 'entertainment', 'interface desi...",https://www.ted.com/talks/david_pogue_simplici...,New York Times columnist David Pogue takes aim...,"(Music: ""The Sound of Silence,"" Simon & Garfun..."
3,53,Greening the ghetto,Majora Carter,18.60,"['MacArthur grant', 'activism', 'business', 'c...",https://www.ted.com/talks/majora_carter_greeni...,"In an emotionally charged talk, MacArthur-winn...",If you're here today â€” and I'm very happy th...
4,66,Do schools kill creativity?,Sir Ken Robinson,19.40,"['children', 'creativity', 'culture', 'dance',...",https://www.ted.com/talks/sir_ken_robinson_do_...,Sir Ken Robinson makes an entertaining and pro...,Good morning. How are you? (Audience) Good. It...

In [31]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4005 entries, 0 to 4004
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   talk_id      4005 non-null   int64
 1   title        4005 non-null   str
 2   speaker_1    4005 non-null   str
 3   duration     4005 non-null   float64
 4   topics       4005 non-null   str
 5   url          4005 non-null   str
 6   description  4005 non-null   str
 7   transcript   4005 non-null   str
dtypes: float64(1), int64(1), str(6)
memory usage: 250.4 KB

In [32]:
df.to_csv('../data/processed/ted_talks_eda.csv',index=False)

### Prepare the Dataset Inspection Report
Create a section in your notebook titled Dataset Inspection Report and answer these questions:

### What is the name and source of the dataset? 
The name of our dataset is ted_talks.csv and its source is Kaggle, an open-source platform.

### How many rows and columns does it contain? 
This dataset contains 4005 records (rows) and 8 columns (attributes).

### How many unique TED Talks are present? 
There are 4005 unique TED talks are present in the dataset.

### Which columns contain text that could be used for recommendations? 
The 'transcripts' column contains the text indicating the talk discussed by the speakers.

### How many values are missing in the important columns? 
There are no any missing values found in any of the columns in the dataset.

### Are there duplicate rows or repeated talk identifiers? 
No any duplicate rows were found during data analysis.

### Are transcripts available for all talks, some talks, or none? 
The transcripts are available for all talks in the dataset.

### What limitations might affect the recommendation system? 
If the 'transcripts' column didn't exist in the dataset, I think this could have been the major limitation which may affect the recommendation system as it is the major understanding portion of any talk by the speakers in the conference.

### Is the dataset suitable for a first content-based recommendation prototype? Explain why. 
Yes, after understanding the raw data to come out with the important features of the dataset, now the dataset looks suitable for a first content-based recommendation prototype.