### Activity 1: Load and Review the Dataset 

 Load the original dataset from data/raw/. 

 Review the findings from Task 2. 

 Identify the fields that require cleaning. 

 Preserve the original dataset without overwriting it.

In [47]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [48]:
df = pd.read_csv("../data/raw/ted_talks.csv")

In [49]:
df.head()

,talk_id,title,speaker_1,duration,topics,url,description,transcript
0,1,Averting the climate crisis,Al Gore,977,"['alternative energy', 'cars', 'climate change...",https://www.ted.com/talks/al_gore_averting_the...,With the same humor and humanity he exuded in ...,"Thank you so much, Chris. And it's truly a gre..."
1,92,The best stats you've ever seen,Hans Rosling,1190,"['Africa', 'Asia', 'Google', 'demo', 'economic...",https://www.ted.com/talks/hans_rosling_the_bes...,You've never seen data presented like this. Wi...,"About 10 years ago, I took on the task to teac..."
2,7,Simplicity sells,David Pogue,1286,"['computers', 'entertainment', 'interface desi...",https://www.ted.com/talks/david_pogue_simplici...,New York Times columnist David Pogue takes aim...,"(Music: ""The Sound of Silence,"" Simon & Garfun..."
3,53,Greening the ghetto,Majora Carter,1116,"['MacArthur grant', 'activism', 'business', 'c...",https://www.ted.com/talks/majora_carter_greeni...,"In an emotionally charged talk, MacArthur-winn...",If you're here today â€” and I'm very happy th...
4,66,Do schools kill creativity?,Sir Ken Robinson,1164,"['children', 'creativity', 'culture', 'dance',...",https://www.ted.com/talks/sir_ken_robinson_do_...,Sir Ken Robinson makes an entertaining and pro...,Good morning. How are you? (Audience) Good. It...

In [50]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4005 entries, 0 to 4004
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   talk_id      4005 non-null   int64
 1   title        4005 non-null   str
 2   speaker_1    4005 non-null   str
 3   duration     4005 non-null   int64
 4   topics       4005 non-null   str
 5   url          4005 non-null   str
 6   description  4005 non-null   str
 7   transcript   4005 non-null   str
dtypes: int64(2), str(6)
memory usage: 250.4 KB

In [51]:
df.shape

(4005, 8)

### Activity 2: Handle Missing Values 

 Identify missing or empty values in important columns. 

 Decide how to handle each issue based on the field's purpose. 

 Do not remove talks with missing transcripts if other useful information is available. 

 Document your decisions and the reason behind each decision.

In [52]:
print(df.isnull().sum())

talk_id        0
title          0
speaker_1      0
duration       0
topics         0
url            0
description    0
transcript     0
dtype: int64

### Activity 3: Remove Duplicate Records 

 Identify exact duplicate rows. 

 Check for repeated talk identifiers or URLs, where available. 

 Verify that repeated records represent the same talk before removing them. 

 Record the number of duplicates identified and removed.

In [53]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [54]:
df.head()

,talk_id,title,speaker_1,duration,topics,url,description,transcript
0,1,Averting the climate crisis,Al Gore,977,"['alternative energy', 'cars', 'climate change...",https://www.ted.com/talks/al_gore_averting_the...,With the same humor and humanity he exuded in ...,"Thank you so much, Chris. And it's truly a gre..."
1,92,The best stats you've ever seen,Hans Rosling,1190,"['Africa', 'Asia', 'Google', 'demo', 'economic...",https://www.ted.com/talks/hans_rosling_the_bes...,You've never seen data presented like this. Wi...,"About 10 years ago, I took on the task to teac..."
2,7,Simplicity sells,David Pogue,1286,"['computers', 'entertainment', 'interface desi...",https://www.ted.com/talks/david_pogue_simplici...,New York Times columnist David Pogue takes aim...,"(Music: ""The Sound of Silence,"" Simon & Garfun..."
3,53,Greening the ghetto,Majora Carter,1116,"['MacArthur grant', 'activism', 'business', 'c...",https://www.ted.com/talks/majora_carter_greeni...,"In an emotionally charged talk, MacArthur-winn...",If you're here today â€” and I'm very happy th...
4,66,Do schools kill creativity?,Sir Ken Robinson,1164,"['children', 'creativity', 'culture', 'dance',...",https://www.ted.com/talks/sir_ken_robinson_do_...,Sir Ken Robinson makes an entertaining and pro...,Good morning. How are you? (Audience) Good. It...

In [55]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4005 entries, 0 to 4004
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   talk_id      4005 non-null   int64
 1   title        4005 non-null   str
 2   speaker_1    4005 non-null   str
 3   duration     4005 non-null   int64
 4   topics       4005 non-null   str
 5   url          4005 non-null   str
 6   description  4005 non-null   str
 7   transcript   4005 non-null   str
dtypes: int64(2), str(6)
memory usage: 250.4 KB

### Activity 4: Clean Text Fields 

Clean the available text fields, such as title, tags, description, and transcript. 

Your preprocessing should include: 

 Converting text to lowercase where appropriate. 

 Removing unnecessary leading, trailing, and repeated whitespace. 

 Handling empty strings and missing text consistently. 

 Applying appropriate punctuation handling without damaging meaningful text.

In [ ]:
import ast # Safely parses a string representation of a Python list, such as the topics values in your dataset.
import html # Converts HTML entities such as &amp; into their readable characters.
import re # Performs pattern-based text cleaning using regular expressions.

In [57]:
df_clean = df.copy()

### We want to standardize text so that irrelevant differences in capitalization, whitespace, or HTML encoding don't unnecessarily affect text analysis.

In [58]:
def clean_text(value, lowercase=True):
    """Clean text while preserving meaningful punctuation."""

    if pd.isna(value):
        return ""

    text = str(value)

    # Decode HTML entities such as &amp; and &quot;
    text = html.unescape(text)

    # Remove HTML tags, if present
    text = re.sub(r"<[^>]+>", " ", text)

    # Remove leading/trailing and repeated whitespace
    text = re.sub(r"\s+", " ", text).strip()

    # Convert to lowercase for consistent text processing
    if lowercase:
        text = text.lower()

    return text

### Each topics value is stored as a string containing a list representation, not as an actual Python list. That's why we need the separate clean_topics() function.

In [ ]:
def clean_topics(value):
    """Convert list-like topics into readable, cleaned text."""

    if pd.isna(value):
        return ""

    # Parse the string -> Python converts the string into an actual list
    if isinstance(value, str):
        try:
            parsed = ast.literal_eval(value) 
            if isinstance(parsed, (list, tuple)):
                value = parsed
        except (ValueError, SyntaxError):
            pass

    ''' Convert individual topics into a single text string Because a recommender system needs the topics to be 
    represented as usable text. '''
    if isinstance(value, (list, tuple)):
        value = " ".join(str(topic) for topic in value)

    return clean_text(value)

In [60]:
# Preserve originals and create cleaned text columns
df_clean["title_clean"] = df_clean["title"].apply(clean_text)
df_clean["speaker_1_clean"] = df_clean["speaker_1"].apply(clean_text)
df_clean["topics_clean"] = df_clean["topics"].apply(clean_topics)
df_clean["description_clean"] = df_clean["description"].apply(clean_text)
df_clean["transcript_clean"] = df_clean["transcript"].apply(clean_text)

In [61]:
print("Original and cleaned text preview:")
display(
    df_clean[
        [
            "title", "title_clean",
            "topics", "topics_clean",
            "description", "description_clean"
        ]
    ].head()
)

Original and cleaned text preview:

,title,title_clean,topics,topics_clean,description,description_clean
0,Averting the climate crisis,averting the climate crisis,"['alternative energy', 'cars', 'climate change...",alternative energy cars climate change culture...,With the same humor and humanity he exuded in ...,with the same humor and humanity he exuded in ...
1,The best stats you've ever seen,the best stats you've ever seen,"['Africa', 'Asia', 'Google', 'demo', 'economic...",africa asia google demo economics global issue...,You've never seen data presented like this. Wi...,you've never seen data presented like this. wi...
2,Simplicity sells,simplicity sells,"['computers', 'entertainment', 'interface desi...",computers entertainment interface design media...,New York Times columnist David Pogue takes aim...,new york times columnist david pogue takes aim...
3,Greening the ghetto,greening the ghetto,"['MacArthur grant', 'activism', 'business', 'c...",macarthur grant activism business cities envir...,"In an emotionally charged talk, MacArthur-winn...","in an emotionally charged talk, macarthur-winn..."
4,Do schools kill creativity?,do schools kill creativity?,"['children', 'creativity', 'culture', 'dance',...",children creativity culture dance education pa...,Sir Ken Robinson makes an entertaining and pro...,sir ken robinson makes an entertaining and pro...

In [62]:
df_clean['topics']

0       ['alternative energy', 'cars', 'climate change...
1       ['Africa', 'Asia', 'Google', 'demo', 'economic...
2       ['computers', 'entertainment', 'interface desi...
3       ['MacArthur grant', 'activism', 'business', 'c...
4       ['children', 'creativity', 'culture', 'dance',...
                              ...
4000    ['activism', 'data', 'technology', 'mental hea...
4001    ['TED-Ed', 'education', 'history', 'animation'...
4002    ['society', 'law', 'policy', 'justice system',...
4003    ['TED-Ed', 'education', 'animation', 'United S...
4004    ['animals', 'TED-Ed', 'animation', 'oceans', '...
Name: topics, Length: 4005, dtype: str

In [63]:
df_clean['topics_clean']

0       alternative energy cars climate change culture...
1       africa asia google demo economics global issue...
2       computers entertainment interface design media...
3       macarthur grant activism business cities envir...
4       children creativity culture dance education pa...
                              ...
4000    activism data technology mental health softwar...
4001    ted-ed education history animation intelligenc...
4002               society law policy justice system tedx
4003    ted-ed education animation united states women...
4004    animals ted-ed animation oceans science educat...
Name: topics_clean, Length: 4005, dtype: str

### Activity 5: Create a Combined Text Field 
Create a new column called combined_text by combining available fields such as title, tags, 
description, and transcript.

### Now we want one column that represents the content of each TED Talk.

In [64]:
# Combine cleaned fields into one text representation
text_columns = [
    "title_clean",
    "topics_clean",
    "description_clean",
    "transcript_clean"
]

In [ ]:
df_clean["combined_text"] = (
    df_clean[text_columns]
    .fillna("")
    .agg(" ".join, axis=1)
    .str.replace(r"\s+", " ", regex=True) # Normalizes repeated whitespace in the combined string.
    .str.strip()
)

In [66]:
# Inspect combined text
display(
    df_clean[
        ["talk_id", "title_clean", "topics_clean", "combined_text"]
    ].head()
)

,talk_id,title_clean,topics_clean,combined_text
0,1,averting the climate crisis,alternative energy cars climate change culture...,averting the climate crisis alternative energy...
1,92,the best stats you've ever seen,africa asia google demo economics global issue...,the best stats you've ever seen africa asia go...
2,7,simplicity sells,computers entertainment interface design media...,simplicity sells computers entertainment inter...
3,53,greening the ghetto,macarthur grant activism business cities envir...,greening the ghetto macarthur grant activism b...
4,66,do schools kill creativity?,children creativity culture dance education pa...,do schools kill creativity? children creativit...

In [68]:
df_clean['combined_text'].head()

0    averting the climate crisis alternative energy...
1    the best stats you've ever seen africa asia go...
2    simplicity sells computers entertainment inter...
3    greening the ghetto macarthur grant activism b...
4    do schools kill creativity? children creativit...
Name: combined_text, dtype: str

In [70]:
print("Total talks:", len(df_clean))

Total talks: 4005

### Activity 6: Save the Cleaned Dataset 

Save the processed dataset to: 

data/processed/ted_talks_cleaned.csv 

Do not overwrite the original file in data/raw/.

In [73]:
df_clean.shape

(4005, 14)

In [77]:
print(df_clean.columns.to_list())

['talk_id', 'title', 'speaker_1', 'duration', 'topics', 'url', 'description', 'transcript', 'title_clean', 'speaker_1_clean', 'topics_clean', 'description_clean', 'transcript_clean', 'combined_text']

In [74]:
df_clean.head()

,talk_id,title,speaker_1,duration,topics,url,description,transcript,title_clean,speaker_1_clean,topics_clean,description_clean,transcript_clean,combined_text
0,1,Averting the climate crisis,Al Gore,977,"['alternative energy', 'cars', 'climate change...",https://www.ted.com/talks/al_gore_averting_the...,With the same humor and humanity he exuded in ...,"Thank you so much, Chris. And it's truly a gre...",averting the climate crisis,al gore,alternative energy cars climate change culture...,with the same humor and humanity he exuded in ...,"thank you so much, chris. and it's truly a gre...",averting the climate crisis alternative energy...
1,92,The best stats you've ever seen,Hans Rosling,1190,"['Africa', 'Asia', 'Google', 'demo', 'economic...",https://www.ted.com/talks/hans_rosling_the_bes...,You've never seen data presented like this. Wi...,"About 10 years ago, I took on the task to teac...",the best stats you've ever seen,hans rosling,africa asia google demo economics global issue...,you've never seen data presented like this. wi...,"about 10 years ago, i took on the task to teac...",the best stats you've ever seen africa asia go...
2,7,Simplicity sells,David Pogue,1286,"['computers', 'entertainment', 'interface desi...",https://www.ted.com/talks/david_pogue_simplici...,New York Times columnist David Pogue takes aim...,"(Music: ""The Sound of Silence,"" Simon & Garfun...",simplicity sells,david pogue,computers entertainment interface design media...,new york times columnist david pogue takes aim...,"(music: ""the sound of silence,"" simon & garfun...",simplicity sells computers entertainment inter...
3,53,Greening the ghetto,Majora Carter,1116,"['MacArthur grant', 'activism', 'business', 'c...",https://www.ted.com/talks/majora_carter_greeni...,"In an emotionally charged talk, MacArthur-winn...",If you're here today â€” and I'm very happy th...,greening the ghetto,majora carter,macarthur grant activism business cities envir...,"in an emotionally charged talk, macarthur-winn...",if you're here today â€” and i'm very happy th...,greening the ghetto macarthur grant activism b...
4,66,Do schools kill creativity?,Sir Ken Robinson,1164,"['children', 'creativity', 'culture', 'dance',...",https://www.ted.com/talks/sir_ken_robinson_do_...,Sir Ken Robinson makes an entertaining and pro...,Good morning. How are you? (Audience) Good. It...,do schools kill creativity?,sir ken robinson,children creativity culture dance education pa...,sir ken robinson makes an entertaining and pro...,good morning. how are you? (audience) good. it...,do schools kill creativity? children creativit...

In [76]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 4005 entries, 0 to 4004
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   talk_id            4005 non-null   int64
 1   title              4005 non-null   str
 2   speaker_1          4005 non-null   str
 3   duration           4005 non-null   int64
 4   topics             4005 non-null   str
 5   url                4005 non-null   str
 6   description        4005 non-null   str
 7   transcript         4005 non-null   str
 8   title_clean        4005 non-null   str
 9   speaker_1_clean    4005 non-null   str
 10  topics_clean       4005 non-null   str
 11  description_clean  4005 non-null   str
 12  transcript_clean   4005 non-null   str
 13  combined_text      4005 non-null   str
dtypes: int64(2), str(12)
memory usage: 438.2 KB

In [72]:
df_clean.to_csv("../data/processed/ted_talks_cleaned.csv")